# Configurações Gerais
WIDTH_WINDOW = 1280;
HEIGHT_WINDOW = 720;
PADX_JANELA = int((1920 - WIDTH_WINDOW)/2);
PADY_JANELA = int((1020 - HEIGHT_WINDOW)/2);
BACKGROUND_JANELA = "#172A3A";
WHITE = "#FFFFFF";

# Cores
MAIN_TONE = "#09BC8A";
LIGHT_TONE = "#EFE7DA";
DARK_TONE = "#172A3A";

# Configurações do Título
TEXTO_TITULO = "Jogo da Velha";
FONTE_TITULO = "Rubik 20";
BACKGROUND_TITULO = MAIN_TONE;
FOREGROUND_TITULO = WHITE;

#Tabuleiro
WIDTH_TABULEIRO = 540;
HEIGHT_TABULEIRO = 540;
PADY_TABULEIRO = 50;
PADX_ESQ_TABULEIRO = 50;
BACKGROUND_TABULEIRO = "#EFE7DA";

#Player Turn
PADX_TURN = 0;
PADY_TURN = 0;
WIDTH_TURN = 500;
HEIGHT_TURN = 333;

#Game Name
WIDTH_GAMENAME = 500;
HEIGHT_GAMENAME = 200;
PADX_GAMENAME = 0;
PADY_TOP_GAMENAME = PADY_TABULEIRO + 30;
PADY_BOTTOM_GAMENAME = 20;

#Select Window
WIDTH_SELECT_WINDOW = 800;
HEIGHT_SELECT_WINDOW = 700;
PADX_SELECT_JANELA = int((1920 - WIDTH_SELECT_WINDOW )/2);
PADY_SELECT_JANELA = int((1020 - HEIGHT_SELECT_WINDOW)/2);

#Select Text
WIDTH_SELECT_TEXT = 700;
HEIGHT_SELECT_TEXT = 210;
PADX_SELECT_TEXT = 0;
PADY_TOP_SELECT_TEXT = 50;
PADY_BOTTOM_SELECT_TEXT= 0;

#Choose Human
WIDTH_CHOOSE_BUTTON = 300;
HEIGHT_CHOOSE_BUTTON = 350;
PADX_CHOOSE_BUTTON = 50;
PADY_CHOOSE_BUTTON = 50;

#Choose Menu
WIDTH_CHOOSE_MENU = 1000;
HEIGHT_CHOOSE_MENU = 800;
PADY_CHOOSE_MENU = 0;
PADX_CHOOSE_MENU = 0;